//import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "cb6f8f47-d202-4929-ad85-308438ea4b1f",
    title:"Ignited Minds",
    author: "A. P. J. Abdul Kalam",
    image:"https://i.ibb.co/G9qbtLk/ignited-minds.png",
    price:199,
    newPrice:"180",
    discount:10,
    Pages: 394,
    Language:"English",
    rating:3.7,
    categoryName:"self-help",
    cashOnDelivery:true,
    fastDelivery:true,
     
  },
  {
    _id: "84b681a3-fbb7-48e5-bed8-25cd63dcefd2",
    title:"Rich Dad Poor Dad ",
    author: "Robert T. Kiyosaki",
    image:"https://i.ibb.co/VNV5QY1/rich-dad-poor-dad.png",
    price:599,
    newPrice:"299",
    discount:50,
    Pages: 334,
    Language:"English",
    rating:4.7,
    categoryName:"self-help",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "d5863589-f0f7-4bbe-b316-8e9b6220a6d0",
    title:"Attitude is Everything:",
    author:"Keller Jeff",
    image:"https://i.ibb.co/JngdDcc/attitude-is-everything.png",
    price:225,
    newPrice:"149",
    discount:33,
    Pages: 144,
    Language:"English",
    rating:4.2,
    categoryName:"self-help",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "5b796868-4182-48f3-9d82-06f321a9504d",
    title:"Think Like a Monk",
    author:"Jay Shetty",
    image:"https://i.ibb.co/7QJ8Tj0/think-like-a-monl.png",
    price:499,
    newPrice:"256",
    discount:48,
    Pages: 328,
    Language:"English",
    rating:4.6,
    categoryName:"self-help",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "4810a571-c205-4ad6-a269-153e433e9194",
    title:"You Can",
    author:"Adams George Matthew",
    image:"https://i.ibb.co/JngdDcc/attitude-is-everything.png",
    price:149,
    newPrice:99,
    discount:33,
    Pages: 232,
    Language:"English",
    rating:2.4,
    categoryName:"self-help",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "5b796868-4182-48f3-9d82-06f321a9504d",
    title:"Zero to One",
    author:"Peter Thiel",
    image:"https://i.ibb.co/YcYcm03/zero-to-one.png",
    price:382,
    newPrice:185,
    discount:51,
    Pages: 212,
    Language:"English",
    rating:4.4,
    categoryName:"self-help",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "3477360f-ca7e-4dff-bcba-807fdc181544",
    title:"Silent Spring",
    author:"Carson Rachel",
    image:"https://i.ibb.co/9hfFx3Q/silent-spring.png",
    price:1482,
    newPrice:1285,
    discount:12,
    Pages: 400,
    Language:"English",
    rating:4,
    categoryName:"Non-Fiction",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "6b2b0fcf-a96e-4ba7-8241-fd9dcac2d339",
    title:"The Richest Man in Babylon ",
    author:"Clason George S.",
    image:"https://i.ibb.co/LZRpj1h/richest-man-in-the-babylon.png",
    price:199,
    newPrice:99,
    discount:50,
    Pages: 400,
    Language:"English",
    rating:4.5,
    categoryName:"Non-Fiction",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "8567c674-4e03-4080-8490-2ca8e147d120",
    title:"Sapiens",
    author:"Harari Yuval Noah",
    image:"https://i.ibb.co/LJLqKnq/sapians.png",
    price:499,
    newPrice:195,
    discount:60,
    Pages: 520,
    Language:"English",
    rating:4.1,
    categoryName:"Non-Fiction",
    cashOnDelivery:false,
    fastDelivery:true, 
  },
  {
    _id: "65297154-a977-4a90-aa70-57a49273ba47",
    title:"Steve Jobs ",
    author:"Steve Jobs ",
    image:"https://i.ibb.co/0DkS3JG/steve-jobs.png",
    price:299,
    newPrice:195,
    discount:50,
    Pages: 568,
    Language:"English",
    rating:4.2,
    categoryName:"Non-Fiction",
    cashOnDelivery:false,
    fastDelivery:true, 
  },
  {
    _id: "eecf6123-9ff1-4d83-aac3-166466464afe",
    title:"Quiet",
    author:"Cain Susan",
    image:"https://i.ibb.co/FgKR2YQ/Quiet.png",
    price:599,
    newPrice:384,
    discount:50,
    Pages: 320,
    Language:"English",
    rating:1.4,
    categoryName:"Non-Fiction",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "9ec5f2d4-b794-4647-b99b-48e83ce1beee",
    title:"Gaban",
    author:"Premchand",
    image:"https://i.ibb.co/hVm6y7X/premchandra.png",
    price:199,
    newPrice:149,
    discount:25,
    Pages: 320,
    Language:"Hindi",
    rating:4.5,
    categoryName:"Non-Fiction",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "664d9372-52af-4734-96d4-a70b3bb90fe7",
    title:"ALL THE LIGHT WE CANNOT SEE",
    author:"Anthony Doerr",
    image:"https://i.ibb.co/YLtwS9R/light-we-can-not-see.png",
    price:559,
    newPrice:349,
    discount:34,
    Pages: 544,
    Language:"Hindi",
    rating:3.9,
    categoryName:"Non-Fiction",
    cashOnDelivery:true,
    fastDelivery:false, 
  },
  {
    _id: "9a347e63-1e49-47ab-820b-8e71280e357a",
    title:"Believe in Yourself",
    author:"Joseph Murphy",
    image:"https://i.ibb.co/nkSyxWK/believe-in-yourself.png",
    price:100,
    newPrice:89,
    discount:11,
    Pages: 54,
    Language:"English",
    rating:4,
    categoryName:"self-help",
    cashOnDelivery:true,
    fastDelivery:true, 
  },
  {
    _id: "6db74792-b7cc-45bf-a462-00eb3e00fa20",
    title:"The Blue Umbrella",
    author:"Bond Ruskin",
    image:"https://i.ibb.co/jR1pHj7/blue-ambrella.png",
    price:"195",
    newPrice:95,
    discount:50,
    Pages: 90,
    Language:"English",
    rating:4.1,
    categoryName:"Fiction",
    cashOnDelivery:false,
    fastDelivery:true, 
  },
  {
    _id: "c1d3e01c-809e-4192-a14b-159ac412948d",
    title:"A Brief History Of Time",
    author:"Stephen Hawking",
    image:"https://i.ibb.co/LS7bzLD/a-brief-history-time.png",
    price:495,
    newPrice:195,
    discount:60,
    Pages: 240,
    Language:"English",
    rating:4.2,
    categoryName:"Fiction",
    cashOnDelivery:false,
    fastDelivery:true, 
  },
  {
    _id: "703b1976-acf4-42e7-811e-1f1bf9308b9c",
    title:"Harry Potter and the Philosopher's Stone",
    author:"Rowling J. K.",
    image:"https://i.ibb.co/rs8tSkP/harry-potter.png",
    price:495,
    newPrice:295,
    discount:40,
    Pages: 350,
    Language:"English",
    rating:4.3,
    categoryName:"Fiction",
    cashOnDelivery:false,
    fastDelivery:true, 
  },
  {
    _id: "af21ac9d-2fe0-45d7-9076-0558e33e7ff6",
    title:"Ikigai",
    author:"HECTER GARCIA",
    image:"https://i.ibb.co/2cpW5r0/ekigai.png",
    price:150,
    newPrice:295,
    discount:70,
    Pages: 150,
    Language:"English",
    rating:4.3,
    categoryName:"Fiction",
    cashOnDelivery:false,
    fastDelivery:true, 
  },
];
